version: "3.9"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: template-db
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432':'5432'
  web:
    image: node-web-app
    depends_on: 
      - db
    ports: 
      - '8080':'8080'