# gcloud builds submit -t gcr.io/ti-is-prodenv-01/is-node-12:v1 --gcs-log-dir=gs://578475024265-cloudbuild-logs-cicd/logs/ .

FROM node:12



gcloud builds submit -t gcr.io/ti-is-prodenv-01/is-wd-evolution-test:v1 --gcs-log-dir=gs://578475024265-cloudbuild-logs-cicd/logs/ .